# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      mkdir .\TEMP\; `
          Invoke-WebRequest -Uri https://aka.ms/vs/16/release/vs_buildtools.exe -OutFile .\TEMP\vs_buildtools.exe; `
          Start-Process .\TEMP\vs_buildtools.exe  -Wait -ArgumentList '--quiet --wait --norestart --nocache `
          --installPath C:\BuildTools `
          --add Microsoft.VisualStudio.Component.VC.CMake.Project `
          --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
          --add Microsoft.VisualStudio.Component.Windows10SDK `
          --add Microsoft.VisualStudio.Component.Windows10SDK.17763'; `
          Remove-Item –path .\TEMP\vs_buildtools.exe

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Binary -Url "https://swift.org/builds/swift-5.4-branch/windows10/swift-5.4-DEVELOPMENT-SNAPSHOT-2021-02-24-a/swift-5.4-DEVELOPMENT-SNAPSHOT-2021-02-24-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
      Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\ucrt\module.modulemap"
      Copy-Item "$env:SDKROOT\usr\share\visualc.modulemap" -destination "$env:VCToolsInstallDir\include\module.modulemap"
      Copy-Item "$env:SDKROOT\usr\share\visualc.apinotes" -destination "$env:VCToolsInstallDir\include\visualc.apinotes"
      Copy-Item "$env:SDKROOT\usr\share\winsdk.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\um\module.modulemap"

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ErrorActionPreference = 'Stop' ; `
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 ; `
          Invoke-WebRequest $('https://github.com/git-for-windows/git/releases/download/v{0}.windows.{1}/MinGit-{0}.{1}-busybox-64-bit.zip' -f 2.15.1, 2) -OutFile 'mingit.zip' -UseBasicParsing ; `
          Expand-Archive mingit.zip -DestinationPath c:\mingit ; `
          Remove-Item mingit.zip -Force ; `
          setx /M PATH $('c:\mingit\cmd;{0}' -f $env:PATH)

- script: |
    .github/install-sqlite.bat
    .github/install-zlib.bat
    swift package update
    swift build -c release
  displayName: 'Run a multi-line script'
