# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

variables:
  toolchain.directory: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain/usr/bin
  bin.directory: C:/Library/Swift-development/bin
  icu.directory: C:/Library/icu-69.1/usr/bin

steps:
- task: PowerShell@2
  timeoutInMinutes: 3
  retryCountOnTaskFailure: 3
  inputs:
    targetType: 'inline'
    script: |
      Install-Binary -Url "https://download.swift.org/swift-5.6.1-release/windows10/swift-5.6.1-RELEASE/swift-5.6.1-RELEASE-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
      Write-Host "##vso[task.prependpath]$(toolchain.directory)"
      Write-Host "##vso[task.prependpath]$(bin.directory)"
      Write-Host "##vso[task.prependpath]$(icu.directory)"
  displayName: Install Swift toolchain

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'aed27b01-a098-473b-9a1b-b8b518639405'
    pipeline: '6'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: 'C:\vcpkg\installed\'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'C:\vcpkg\installed\x64-windows\bin'
    Contents: '*.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy build artifacts to staging directory

- task: BatchScript@1
  inputs:
    filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
    arguments: -no_logo -arch=x64 -host_arch=x64
    modifyEnvironment: true
  displayName: Setup developer environment

- script: |
    swift package update
    swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors -Xswiftc -LC:/vcpkg/installed/x64-windows/lib/ -Xcc -IC:/vcpkg/installed/x64-windows/include/
  env:
    SDKROOT: C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
    DEVELOPER_DIR: C:\Library\Developer
  timeoutInMinutes: 15
  continueOnError: true
  displayName: Build Swift package

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\.build\x86_64-unknown-windows-msvc\release'
    contents: |
      *.exe
      *.dll
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: Copy build artifacts to staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: x86_64-unknown-windows-msvc-release
  displayName: Publish build artifacts
