# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: BatchScript@1
  displayName: VsDevCmd
  inputs:
    filename: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat
    arguments: -no_logo -arch=x64 -host_arch=x64
    modifyEnvironment: true

- script: |
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/ucrt.modulemap" -o "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/visualc.modulemap" -o "%VCToolsInstallDir%\include\module.modulemap"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/visualc.apinotes" -o "%VCToolsInstallDir%\include\visualc.apinotes"
    curl -L "https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Platform/winsdk.modulemap" -o "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
  displayName: Configure SDK
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Binary -Url "https://swift.org/builds/swift-5.4-branch/windows10/swift-5.4-DEVELOPMENT-SNAPSHOT-2021-02-24-a/swift-5.4-DEVELOPMENT-SNAPSHOT-2021-02-24-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
  displayName: Install Swift toolchain

- script: |
    .github/install-sqlite.bat
    .github/install-zlib.bat
    swift package update
    swift build -c release
  displayName: 'Install dependencies'

- script: |
    swift package update
  displayName: 'Update swift package dependencies'

- script: |
    swift package update
  displayName: 'Build swift package'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'release'
    downloadPath: '$(System.ArtifactsDirectory)'