# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  toolchain.directory: C:/Library/Developer/Toolchains/unknown-Asserts-development.xctoolchain
  sdk.directory: C:/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk
  runtime.directory: "C:/Program Files/swift/runtime-development/usr/bin"
  icu.directory: "C:/Program Files/swift/icu-69.1/usr/bin"

steps:
- task: PowerShell@2
  timeoutInMinutes: 3
  retryCountOnTaskFailure: 3
  inputs:
    targetType: 'inline'
    script: |
      Install-Binary -Url "https://download.swift.org/swift-5.7.3-release/windows10/swift-5.7.3-RELEASE/swift-5.7.3-RELEASE-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
  displayName: Install Swift toolchain

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: specific
    project: '3133d6ab-80a8-4996-ac4f-03df25cd3224'
    allowPartiallySucceededBuilds: true
    pipeline: 1
    artifactName: 'zlib-${{ parameters.platform }}-${{ parameters.host }}'
    downloadPath: '$(System.ArtifactsDirectory)'
  displayName: Download zlib

- task: CopyFiles@2
  inputs:
    SourceFolder: 'C:\vcpkg\installed\x64-windows\bin'
    Contents: '*.dll'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy build artifacts to staging directory

- task: BatchScript@1
  inputs:
    filename: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/Tools/VsDevCmd.bat
    arguments: -no_logo -arch=x64 -host_arch=x64
    modifyEnvironment: true
  displayName: Setup developer environment

- script: |
    echo ##vso[task.prependpath]$(toolchain.directory)/usr/bin
    echo ##vso[task.prependpath]$(runtime.directory)
    echo ##vso[task.prependpath]$(icu.directory)
  displayName: Update PATH

- script: |
    swift package update
    swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors -Xswiftc -L$(System.ArtifactsDirectory)/usr/lib/ -Xcc -I$(System.ArtifactsDirectory)/usr/include/
  env:
    SDKROOT: C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk
    DEVELOPER_DIR: C:\Library\Developer
  timeoutInMinutes: 15
  continueOnError: true
  displayName: Build Swift package

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)\.build\x86_64-unknown-windows-msvc\release'
    contents: |
      *.exe
      *.dll
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: Copy build artifacts to staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: x86_64-unknown-windows-msvc-release
  displayName: Publish build artifacts
