name: CI – Ubuntu

on: [push]

jobs:
  continuous-integration:

    runs-on: [ubuntu-18.04]

    steps:

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Show compiler version
      run: swift --version

    - name: Update package dependencies
      run: swift package update

    - name: Build Debug mode
      run: swift build --build-tests

    - name: Run tests
      run: swift test
