name: CI – Ubuntu

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [ubuntu-18.04]

    steps:

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Checkout libxlsxwriter
      uses: actions/checkout@v2
      with: 
        repository: jmcnamara/libxlsxwriter
        ref: 'RELEASE_1.1.4'
        path: libxlsxwriter
        
    - name: Build libxlsxwriter
      working-directory: ./libxlsxwriter
      run: |
        make
        sudo make install
        sudo ldconfig

    - name: Get the lines of code.
      id: scc
      uses: iryanbell/scc-docker-action@v1.0.0
      with:
        args: ${{ env.workspace }} -i swift

    - name: Update package dependencies
      run: swift package update

    - name: Run tests
      run: swift test

