name: CI – Ubuntu

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 5
    runs-on: [ubuntu-20.04]

    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Checkout libxlsxwriter
      uses: actions/checkout@v3
      with: 
        repository: jmcnamara/libxlsxwriter
        ref: 'RELEASE_1.1.5'
        path: libxlsxwriter

    - name: Cache libxlsxwriter
      id: cache-libxlsxwriter
      uses: actions/cache@v3
      with:
        path: ./libxlsxwriter
        key: ${{ runner.os }}-libxlsxwriter

    - name: Build libxlsxwriter
      working-directory: ./libxlsxwriter
      run: |
        make
        sudo make install
        sudo ldconfig

    - name: Update package dependencies
      run: swift package update

    - name: Build tests
      run: swift build --build-tests -Xswiftc -suppress-warnings

    - name: Run tests
      run: swift test -Xswiftc -suppress-warnings
