name: CI – Ubuntu 2

on: push
env: 
  SPM: spm
jobs:
  continuous-integration:
    timeout-minutes: 5
    runs-on: [ubuntu-22.04]

    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Update package dependencies
      run: swift package update

    - name: Build tests
      run: swift build --build-tests -Xswiftc -suppress-warnings

    - name: Run tests
      run: swift test -Xswiftc -suppress-warnings

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: Test_Results
        path: |
          *.png

