name: CI – Ubuntu

on: [push]

jobs:
  continuous-integration:

    runs-on: [ubuntu-18.04]

    steps:

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Show compiler version
      run: swift --version

    - name: Get the lines of code.
      id: scc
      uses: iryanbell/scc-docker-action@v1.0.0
      with: 
        args: ${{ env.workspace }} -i swift

    - name: Update package dependencies
      run: swift package update

    - name: Build Debug mode
      run: swift build --build-tests

    - name: Run tests
      run: swift test

    - name: Generate Documentation
      uses: SwiftDocOrg/swift-doc@master
      with:
        module-name: BlackBoxModel
    
    - name: Upload Documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: ./.build/documentation
