name: CI – Windows

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2022]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9.2-release
          tag: 5.9.2-RELEASE

      - name: Build Release Mode
        run: swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -Ilibxlsxwriter\include -Xlinker -Llibxlsxwriter\lib -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\*.exe
            .build\x86_64-unknown-windows-msvc\release\*.dll
