name: CI – Windows

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2022]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Checkout libxlsxwriter
        uses: actions/checkout@v3
        with: 
          repository: jmcnamara/libxlsxwriter
          ref: 'RELEASE_1.1.5'
          path: libxlsxwriter

      - name: Install dependencies
        working-directory: libxlsxwriter
        shell: cmd
        run: |
          vcpkg.exe install zlib:x64-windows sqlite3:x64-windows
          vcpkg.exe integrate install



      - name: CMake libxlsxwriter
        working-directory: libxlsxwriter
        shell: cmd
        run: |
          cd cmake
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DUSE_DTOA_LIBRARY=ON -DUSE_NO_MD5=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64
          cmake --build . --config Release
        continue-on-error: true

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8-release
          tag: 5.8-RELEASE


      - name: Build Release Mode
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xcc -Llibxlsxwriter/include -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors
        continue-on-error: true

      - name: Copy libs to build folder
        run: Copy-Item -Path "C:\vcpkg\installed\x64-windows\bin\*.dll" -Destination "D:\a\SPC\SPC\.build\x86_64-unknown-windows-msvc\release" -Recurse
        continue-on-error: true
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\*.exe
            .build\x86_64-unknown-windows-msvc\release\*.dll
