name: CI – Windows

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2019]

    steps:

      - name: vcpkg install libxlsxwriter
        run: vcpkg install libxlsxwriter:x64-windows
        continue-on-error: true

      - name: vcpkg install sqlite3
        run: vcpkg install sqlite3:x64-windows
        continue-on-error: true

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5.3-release
          tag: 5.5.3-RELEASE

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build Release Mode
        run: swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors -Xswiftc -LC:/vcpkg/installed/x64-windows/lib/
        continue-on-error: true

      - name: Compress exe binaries 
        uses: damuellen/upx-action@master
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\*.exe
          args: -9
          strip: false

      - name: Copy libs to workspace
        run: Copy 'C:\vcpkg\installed\x64-windows\bin' '.build\x86_64-unknown-windows-msvc\release'
        shell: powershell

      - name: Compress dll binaries 
        uses: damuellen/upx-action@master
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\*.dll
          args: -9
          strip: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\*.exe
            .build\x86_64-unknown-windows-msvc\release\*.dll
            ${{GITHUB_WORKSPACE}}\bin\*.dll
