name: CI – Windows

on: workflow_dispatch

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2022]

    steps:
      - name: vcpkg install libxlsxwriter
        run: vcpkg install libxlsxwriter:x64-windows

      - name: vcpkg install sqlite3
        run: vcpkg install sqlite3:x64-windows

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.8-release
          tag: 5.8-RELEASE

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build Release Mode
        run: swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors -Xswiftc -LC:/vcpkg/installed/x64-windows/lib/ -Xcc -IC:/vcpkg/installed/x64-windows/include/
        continue-on-error: true

      - name: Copy libs to build folder
        run: Copy-Item -Path "C:\vcpkg\installed\x64-windows\bin\*.dll" -Destination "D:\a\SPC\SPC\.build\x86_64-unknown-windows-msvc\release" -Recurse
        continue-on-error: true
        shell: powershell

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\*.exe
            .build\x86_64-unknown-windows-msvc\release\*.dll
