name: CI – Windows

on: [push]

jobs:
  continuous-integration:

    runs-on: [windows-latest]

    steps:

      - name: Setup Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Swift compiler
        run: |
          Install-Binary -Url "https://swift.org/builds/swift-5.4-branch/windows10/swift-5.4-DEVELOPMENT-SNAPSHOT-03-25-a/swift-5.4-DEVELOPMENT-SNAPSHOT-03-25-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")

      - name: Set Environment Variables
        run: |
          echo "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "DEVELOPER_DIR=C:\Library\Developer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Adjust Paths
        run: |
          echo "C:\Library\Swift-development\bin;C:\Library\icu-67\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Supporting Files
        run: |
          Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\ucrt\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.modulemap" -destination "$env:VCToolsInstallDir\include\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.apinotes" -destination "$env:VCToolsInstallDir\include\visualc.apinotes"
          Copy-Item "$env:SDKROOT\usr\share\winsdk.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\um\module.modulemap"

      - name: Update package dependencies
        run: swift package update

      - name: Build Release Mode
        run: swift build -c release

      - name: Strip symbols
        shell: cmd
        run: FOR %%f IN (.build\x86_64-unknown-windows-msvc\release\*.exe) DO llvm-strip %%f

      - name: Compress SolarPerformanceCalc
        uses: svenstaro/upx-action@v2
        with:
          file: .build\x86_64-unknown-windows-msvc\release\SolarPerformanceCalc.exe
          args: -9
          strip: false

      - name: Compress SolarFieldCalc
        uses: svenstaro/upx-action@v2
        with:
          file: .build\x86_64-unknown-windows-msvc\release\SolarFieldCalc.exe
          args: -9
          strip: false

      - name: Compress TransTES
        uses: svenstaro/upx-action@v2
        with:
          file: .build\x86_64-unknown-windows-msvc\release\TransTES.exe
          args: -9
          strip: false

      - name: Compress PinchPointTool
        uses: svenstaro/upx-action@v2
        with:
          file: .build\x86_64-unknown-windows-msvc\release\PinchPointTool.exe
          args: -9
          strip: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\SolarPerformanceCalc.exe
            .build\x86_64-unknown-windows-msvc\release\SolarFieldCalc.exe
            .build\x86_64-unknown-windows-msvc\release\TransTES.exe
            .build\x86_64-unknown-windows-msvc\release\PinchPointTool.exe
