name: CI – Windows

on: push

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2022]

    steps:

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.7.3-release
          tag: 5.7.3-RELEASE

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Create directory
        run: mkdir ${{github.workspace}}\build
        shell: cmd

      - name: Install zlib
        working-directory: ${{github.workspace}}/build
        run: ${{github.workspace}}/.github/workflows/install_zlib.bat
        shell: cmd

      - name: Build Release Mode
        run: swift build -c release -Xlinker /INCREMENTAL:NO -Xlinker /IGNORE:4217 -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors -Xswiftc -L%PROGRAMFILES%\zlib\lib -Xcc -I%PROGRAMFILES%\zlib\include\ 
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\*.exe
            .build\x86_64-unknown-windows-msvc\release\*.dll
