name: Continuous Integration – Windows

on: [push]

jobs:
  continuous-integration:

    runs-on: [windows-latest]

    steps:

      - uses: actions/checkout@v2
        
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
        
      - name: Install Swift (Swift Toolchain)
        run: |
          Install-Binary -Url "https://swift.org/builds/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2020-09-22-a/swift-DEVELOPMENT-SNAPSHOT-2020-09-22-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
          echo "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "DEVELOPER_DIR=C:\Library\Developer" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Library\Swift-development\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append 
          echo "C:\Library\icu-67\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Install Swift (Windows SDK)
        shell: cmd
        run: |
          copy "%SDKROOT%\usr\share\ucrt.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
          copy "%SDKROOT%\usr\share\visualc.modulemap" "%VCToolsInstallDir%\include\module.modulemap"
          copy "%SDKROOT%\usr\share\visualc.apinotes" "%VCToolsInstallDir%\include\visualc.apinotes"
          copy "%SDKROOT%\usr\share\winsdk.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
          
      - name: "Install SQLite"
        shell: cmd
        run: .github/install-sqlite.bat
        
      - name: Build Release Mode
        run: swift build -v -c release --enable-test-discovery -Xlinker /INCREMENTAL:NO -Xswiftc -LC:\sqlite
        
      - uses: actions/upload-artifact@v2
        with:
          name: SPC-win32-x64
          path: |
            D:\a\SPC\SPC\.build\x86_64-unknown-windows-msvc\release\SolarPerformanceCalc.exe
            D:\a\SPC\SPC\.build\x86_64-unknown-windows-msvc\release\SwiftToolsSupport.dll
