name: Continuous Integration – Windows

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install Swift (Swift Toolchain)
        run: |
          Install-Binary -Url "https://swift.org/builds/development/windows10/swift-DEVELOPMENT-SNAPSHOT-2020-09-22-a/swift-DEVELOPMENT-SNAPSHOT-2020-09-22-a-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
          echo "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "DEVELOPER_DIR=C:\Library\Developer" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Library\Swift-development\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append 
          echo "C:\Library\icu-67\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Swift (Windows SDK)
        shell: cmd
        run: |
          copy "%SDKROOT%\usr\share\ucrt.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\ucrt\module.modulemap"
          copy "%SDKROOT%\usr\share\visualc.modulemap" "%VCToolsInstallDir%\include\module.modulemap"
          copy "%SDKROOT%\usr\share\visualc.apinotes" "%VCToolsInstallDir%\include\visualc.apinotes"
          copy "%SDKROOT%\usr\share\winsdk.modulemap" "%UniversalCRTSdkDir%\Include\%UCRTVersion%\um\module.modulemap"
      - name: "Install SQLite"
        shell: cmd
        run: .github/install-sqlite.bat
      - name: Build
        run: swift build -c release --enable-test-discovery -Xlinker /INCREMENTAL:NO -Xswiftc -IC:\sqlite -Xswiftc -LC:\sqlite
