name: CI – Windows

on: [push]

jobs:
  continuous-integration:
    timeout-minutes: 15
    runs-on: [windows-2019]

    steps:

      - name: vcpkg install libxlsxwriter
        run: vcpkg install libxlsxwriter:x64-windows
        continue-on-error: true

      - name: Setup Swift compiler
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5.2-release
          tag: 5.5.2-RELEASE

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build Release Mode
        run: swift build -c release -Xswiftc -gnone -Xswiftc -suppress-warnings -Xswiftc -continue-building-after-errors
        continue-on-error: true

      - name: Compress SolarPerformanceCalc
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\SPC.exe
          args: -9
          strip: false

      - name: Compress SolarFieldCalc
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\SolarFieldCalc.exe
          args: -9
          strip: false

      - name: Compress TransTES
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\TransTES.exe
          args: -9
          strip: false

      - name: Compress SunOl
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\SunOl.exe
          args: -9
          strip: false

      - name: Compress PinchPointTool
        uses: svenstaro/upx-action@v2
        continue-on-error: true
        with:
          file: .build\x86_64-unknown-windows-msvc\release\PinchPointTool.exe
          args: -9
          strip: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        continue-on-error: true
        with:
          name: SPC-win32-x64
          path: |
            .build\x86_64-unknown-windows-msvc\release\SPC.exe
            .build\x86_64-unknown-windows-msvc\release\SolarFieldCalc.exe
            .build\x86_64-unknown-windows-msvc\release\TransTES.exe
            .build\x86_64-unknown-windows-msvc\release\PinchPointTool.exe
            .build\x86_64-unknown-windows-msvc\release\SunOl.exe
